// This file was automatically generated by the Soy compiler.
// Please don't edit this file by hand.
// source: com/foo/bonjour.soy

/**
 * @fileoverview Templates in namespace com.foo.
 * @public
 */

 goog.provide('com.foo');

 goog.requireType('goog.soy');
 goog.require('soydata.VERY_UNSAFE');
 
 
 /**
  * @param {Object<string, *>=} opt_data
  * @param {(?goog.soy.IjData|?Object<string, *>)=} opt_ijData
  * @param {(?goog.soy.IjData|?Object<string, *>)=} opt_ijData_deprecated
  * @return {!goog.soy.data.SanitizedHtml}
  * @suppress {checkTypes}
  */
 com.foo.bonjour = function(opt_data, opt_ijData, opt_ijData_deprecated) {
   opt_ijData = /** @type {!goog.soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
   return soydata.VERY_UNSAFE.ordainSanitizedHtml('Bonjour, le monde!');
 };
 if (goog.DEBUG) {
   com.foo.bonjour.soyTemplateName = 'com.foo.bonjour';
 }
 